### ISSUE TITLE
EaselJS?

### ISSUE THREAD

**Issue by kauffmanes** [yodahuang/react-nav2djs#1]
Question - did you have to use EaselJS for this? The docs say this requires it, but I haven't figured out if I actually need it.

**Comment by yodahuang** [comment]
I'm afraid yes, since it's one of the dependencies for [nav2djs](https://github.com/GT-RAIL/nav2djs). But this project has already declared these dependencies in `package.json`, so you can install them using `npm` or `yarn` very easily, no need for including these libraries in your frontend explicitly, as is suggested by the original `nav2djs` doc.
